### ISSUE TITLE
寻求完整代码

### ISSUE THREAD

**Issue by devil1213** [stevenXS/yolov5_rotation_anchor_based#1]
## ❔Question
作者你好 我运行这份代码有问题 请问您有完整的代码吗

**Comment by stevenXS** [comment]
稍等我发一份到你的邮箱，因为这份代码还在开发中。

**Comment by devil1213** [comment]
哇 速度好快 感谢

**Comment by stevenXS** [comment]
您发下您的邮箱ID




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月6日(星期一) 下午4:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [stevenXS/yolov5_rotation_anchor_based] 寻求完整代码 (Issue #1)





 
哇 速度好快 感谢

**Comment by devil1213** [comment]
devil_135@163.com

**Comment by devil1213** [comment]
***@***.*** 麻烦大佬了



在 2021-12-06 17:00:02，"steven" ***@***.***> 写道：

您发下您的邮箱ID




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;;
发送时间: 2021年12月6日(星期一) 下午4:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;; ***@***.***&gt;;
主题: Re: [stevenXS/yolov5_rotation_anchor_based] 寻求完整代码 (Issue #1)






哇 速度好快 感谢

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by stevenXS** [comment]
@devil1213 不客气，已发送

**Comment by devil1213** [comment]
十分谢谢 已经收到QAQ
